name: nidn
channels:
- conda-forge
- pytorch
dependencies:
- cudatoolkit>=11.0.221
- dotmap>=1.3.24
- loguru>=0.5.3
- matplotlib>=3.3.3
- pandas>=1.3.1
- pytest>=6.2.1
- python>=3.8
- pytorch>=1.9
- scipy>=1.6.0
- sphinx>=3.4.3
- sphinx_rtd_theme>=0.5.1
- tqdm>=4.56.0
- toml>=0.10.2