# Training Properties
seed = 42
model_type = "siren"
iterations = 2000
learning_rate = 6.5e-5
type = "classification" # "classification" or "regression"
reg_loss_weight = 0.05 # weighting of the regularization loss
use_regularization_loss = true # only relevant for classification

# Loss
L = 2.0
absorption_loss = false

# Model Parameters
n_neurons = 100
hidden_layers = 9
encoding_dim = 4
siren_omega = 1.0

# Epsilon Properties
add_noise = false
noise_scale = 0.05
eps_oversampling = 1
real_min_eps = 1e-3
real_max_eps = 20.0
imag_min_eps = 0.0
imag_max_eps = 5.0

# Grid dimensions
Nx = 5
Ny = 5
N_layers = 1

# Target frequencies
physical_wavelength_range = [250e-9,10e-6]
N_freq = 20
